- hosts: server

  roles:
    - { role: gurkalov.deploy_user, tags: user }
    - { role: gurkalov.php_fpm, tags: php, become: yes }
    - { role: geerlingguy.nginx, tags: nginx, become: yes }
    - { role: geerlingguy.redis, tags: redis, become: yes }
